version: '3.8'

services:
  multistream:
    build: .
    container_name: multistream-server
    ports:
      - "1935:1935"    # RTMP port
      - "8000:8000"    # HTTP API/Dashboard port
      - "9000:9000"    # HTTP Streaming port
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
      - ./recordings:/app/recordings
    restart: unless-stopped